# Generated by Django 4.2.7 on 2023-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage_discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
