# Generated by Django 4.2.7 on 2023-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('discount_percent', models.SmallIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
